// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcStation.Data;

#nullable disable

namespace MVCCitybike.Migrations
{
    [DbContext(typeof(MvcStationContext))]
    [Migration("20230525195841_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("MVCCitybike.Models.Station", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adress")
                        .HasColumnType("TEXT");

                    b.Property<int>("FID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kapasiteet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kaupunki")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Namn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nimi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operaattor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Osoite")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stad")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("x")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("y")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Station");
                });
#pragma warning restore 612, 618
        }
    }
}
