// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcStation.Data;

#nullable disable

namespace MVCCitybike.Migrations
{
    [DbContext(typeof(MvcStationContext))]
    partial class MvcStationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCCitybike.Models.Station", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FID")
                        .HasColumnType("int");

                    b.Property<int>("Kapasiteet")
                        .HasColumnType("int");

                    b.Property<string>("Kaupunki")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Kuva")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Citybike aseman nimi");

                    b.Property<string>("Operaattor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Osoite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("x")
                        .HasColumnType("decimal(8, 6)");

                    b.Property<decimal>("y")
                        .HasColumnType("decimal(9, 6)");

                    b.HasKey("ID");

                    b.ToTable("Station");
                });
#pragma warning restore 612, 618
        }
    }
}
