// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcBiketripsMay2021.Data;

#nullable disable

namespace MVCCitybike.Migrations.MvcBiketripsMay2021
{
    [DbContext(typeof(MvcBiketripsMay2021Context))]
    [Migration("20230616201927_EkaMigrate")]
    partial class EkaMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCCitybike.Models.BiketripsMay2021", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Covered_distance_m")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2");

                    b.Property<int>("Departure_station_id")
                        .HasColumnType("int");

                    b.Property<string>("Departure_station_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration_sec")
                        .HasColumnType("int");

                    b.Property<DateTime>("Return")
                        .HasColumnType("datetime2");

                    b.Property<int>("Return_station_id")
                        .HasColumnType("int");

                    b.Property<string>("Return_station_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BiketripsMay2021");
                });
#pragma warning restore 612, 618
        }
    }
}
